Added menu items, with some functionality
mali891/zangief-todos pull request #8
Opened 2020-01-10 14:49 UTC by TurnbulA

Menu buttons have some functionality. When clicked first two buttons show which filter/ sort is applied 
Search button takes in data using enter key or button

2020-01-10 14:53 UTC, mali891 commented on index.html
> +      <section class="todo-list-menu">
These class names are quite confusing, let's catch up on Monday about them

2020-01-10 14:55 UTC, TurnbulA commented on index.html
> +      <section class="todo-list-menu">
ok

2020-01-10 14:57 UTC, mali891 commented on todos.js
> +      reset.style.display = "block";
Toggle classes rather than inline properties

2020-01-10 15:05 UTC, mali891 commented
I just pulled the branch, good job so far @TurnbulA . I think some of the JS can be written a little bit cleaner, and it looks like there are some minor bugs in the UI. Let's catch up on Monday and go through them

2020-01-13 13:15 UTC, sjalgeo commented on index.html
> +      <section class="c-header">
this must have been a huge PITA to retro fit, well done for not wrecking it.

2020-01-13 13:23 UTC, mali891 commented on index.html
> +        <h1 class="c-header-heading">To do list</h1v b>
`</h1v b>` ?

2020-01-13 13:24 UTC, mali891 commented on index.html
> +        <div class="c-menu-control c-menu-item--filter">
There's a few modifiers in here (`--`), I'm not convinced there should be. Is there a good reason to have them in?

2020-01-13 13:25 UTC, mali891 commented on index.html
> +          <div class="c-menu-control-active">
`--active` could be a modifier

2020-01-13 13:27 UTC, mali891 commented on index.html
> +            <p class="c-menu-control-active-text"></p>
That doesn't sound right

2020-01-16 13:00 UTC, mali891 commented on index.html
> +            class="c-menu-control__dropdown--content c-menu-control__dropdown-sort"
modifier

2020-01-16 13:00 UTC, mali891 requested changes

2020-01-16 13:00 UTC, mali891 commented on index.html
>          <div class="c-menu-control c-menu-item--sort">
modifier

2020-01-20 10:29 UTC, mali891 commented on index.html
> +            <div class="c-menu__dropdown-content c-menu__dropdown-sort">
These could probably be `ul` > `li`

2020-01-20 10:29 UTC, mali891 commented on index.html
> +          <div class="c-menu-status--active">
How did you come up with the name for this?

2020-01-20 10:58 UTC, mali891 approved these changes

2020-01-20 10:59 UTC, merged